---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/

---
spring:
  profiles: verb
  
---
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  
---
words: a,the
